services:
  - type: web
    name: rine-forge-api
    env: docker
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 20.11.0
      - key: DATABASE_URL
        sync: false
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: SENDER_NAME
        value: Alex Rine
      - key: SENDER_EMAIL
        value: alexrine691@gmail.com
      - key: SENDER_COMPANY
        value: Rine Forge Systems
      - key: DRY_RUN
        value: 'False'
